discussion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls'))
]

todolist/urls.py
from django.urls import path
from . import views

# Adding a namespace to this urls.py help django distinguish this set of routes from other urls.py files in other packages.
app_name = 'todolist'
urlpatterns = [
	# localhost:8000/todolist/
	path('', views.index, name="index"),
	path('<int:todoitem_id>/', views.todoitem, name="viewtodoitem"),
	path('add_task/', views.add_task, name="add_task"),
	path('add_event/', views.add_event, name="add_event"),
	path('<int:eventitem_id>/event', views.eventitem, name="vieweventitem"),
	path('update_profile/', views.update_profile, name="update_profile"),
	path('login/', views.login_view, name="login"),
	path('register/', views.register, name="register"),
	path('logout/', views.logout_view, name="logout"),
	path('<int:todoitem_id>/update', views.update_task, name="update_task"),
	path('<int:todoitem_id>/delete', views.delete_task, name="delete_task")
]	

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

# Create your models here.

def return_date_time():
    now = timezone.now()
    return now + timedelta(days=1)

class ToDoItem(models.Model):
	# CharField = String value
	# DateTimeField = Datetime datatype
	task_name = models.CharField(max_length = 50)
	description = models.CharField(max_length = 200)
	status = models.CharField(max_length = 50, default = "Pending")
	date_created = models.DateTimeField("Date Created")
	# Adding a user_id to the ToDoItem table, which is a foreign key connected to the Users table.
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")


class EventItem(models.Model):
	event_name = models.CharField(max_length = 50)
	description = models.CharField(max_length = 200)
	status = models.CharField(max_length = 50, default = "Pending")
	event_date = models.DateField(default=return_date_time)
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label="Username", max_length="20")
	password = forms.CharField(label="Password", max_length="20")

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length="50")
	description = forms.CharField(label="Description", max_length="500")

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length="50")
	description = forms.CharField(label="Description", max_length="500")
	status = forms.CharField(label="Status", max_length="50")

class AddEventForm(forms.Form):
	event_name = forms.CharField(label="Event Name", max_length="50")
	description = forms.CharField(label="Description", max_length="500")
	event_date = forms.DateField(label="Event Date")

class UpdateProfileForm(forms.Form):
	first_name = forms.CharField(label="First Name", max_length="30")
	last_name = forms.CharField(label="Last Name", max_length="30")
	password = forms.CharField(label="Password", max_length="20")

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader 
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

# We import the built-in 'User' model to be able to do operations to the built-in Users table from Django.
from django.contrib.auth.models import User
from .models import ToDoItem, EventItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, AddEventForm, UpdateProfileForm

# Create your views here.
def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	eventitem_list = EventItem.objects.filter(user_id=request.user.id)
	todoexists = todoitem_list.exists()
	eventexists = eventitem_list.exists()
	
	template = loader.get_template('todolist/index.html')

	context = {
		'todoitem_list': todoitem_list,
		'eventitem_list': eventitem_list,
		'todoexists': todoexists,
		'eventexists': eventexists,
		'user': request.user
	}

	return HttpResponse(template.render(context, request))

	# You can also render a template using this way
	# return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	# 'model_to_dict' function translates a data model into a python dictionary (object). This is so that we can use the data as a regular object/dictionary.
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	# try: 
	# 	todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
	# except ToDoItem.DoesNotExist:
	# 	return HttpResponse("Error: Task Not Found")

	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

	# ACTIVITY (until 9:35PM)
	# 1. Create a todoitem template
	# 2. In the template, show the 'task_name', 'description', 'status' of the todo item. (each enlosed in an HTML tag)
	# 3. At the end of the template, create an anchor tag that will return the user to the 'index' page


def eventitem(request, eventitem_id):

	eventitem = get_object_or_404(EventItem, pk=eventitem_id)

	return render(request, "todolist/eventitem.html", model_to_dict(eventitem))


def register(request):
	users = User.objects.all()
	is_user_registered = False
	
	# Loops through each existing user and checks if they already exist in the table
	# for individual_user in users:
	# 	if individual_user.username == "johndoe":
	# 		is_user_registered = True
	# 		break

	# The context 'is_user_registered' is put after the for loop in order for it to get the updated value if 'for' loop above equals to True.
	context = {
		"is_user_registered": is_user_registered
	}

	if is_user_registered == False:
		# 1. Creating a new instance of the User model.
		user = User()

		# 2. Assign data values to each property of the model.
		user.username = "johndeex"
		user.first_name = "John"
		user.last_name = "Dee"
		user.email = "johndee@email.com"
		user.set_password("johndoe1")
		user.is_staff = False
		user.is_active = True

		# 3. Save the new instance of a user into the database.
		user.save()

		# The context will be the data to be passed to the template
		context = {
			"first_name": user.first_name,
			"last_name": user.last_name
		}

	return render(request, "todolist/register.html", context)

def update_profile(request):
	context = {
		"user": request.user,
		"first_name": request.user.first_name,
		"last_name": request.user.last_name,
		"password": ""
	}

	if request.method == 'POST':
		form = UpdateProfileForm(request.POST)

		if form.is_valid() == False:
			form = UpdaProfileForm()

		else:

			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password']

			if request.user:

				request.user.first_name = first_name
				request.user.last_name = last_name
				request.user.set_password(password)
				request.user.save()
				return redirect("todolist:index")

			else:

				context = {
				    "error": True
				}

	return render(request, "todolist/update_profile.html", context)


def login_view(request):
	context = {}

	if request.method == 'POST':
		# request.POST contains all the fields coming from the Login.html form
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username=username, password=password)

			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				# The 'login' function saves the user's ID in Django's session. The request will be the one that handles the user's data and we can access the user by using 'request.user'.
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					"error":  True
				}

	return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")


def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:
				ToDoItem.objects.create(
					task_name=task_name,
					description=description,
					date_created=timezone.now(),
					user_id=request.user.id
				)

				return redirect('todolist:index')

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)


def update_task(request, todoitem_id):
	# Returns a queryset
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    context = {
        "user": request.user,
        "todoitem_id": todoitem_id,
        # Accessing the first element is necessary because the "ToDoItem.objects.filter()" method returns a queryset
        "task_name": todoitem[0].task_name,
        "description": todoitem[0].description,
        "status": todoitem[0].status
    }

    if request.method == 'POST':

        form = UpdateTaskForm(request.POST)

        if form.is_valid() == False:

            form = UpdateTaskForm()

        else:

            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']
            
            if todoitem:

                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/update_task.html", context)


def delete_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    todoitem.delete()

    return redirect("todolist:index")



def add_event(request):
	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			event_date = form.cleaned_data['event_date']
			duplicates = EventItem.objects.filter(event_name=event_name)

			if not duplicates:
				EventItem.objects.create(
					event_name=event_name,
					description=description,
					event_date=event_date,
					user_id=request.user.id
				)

				return redirect('todolist:index')

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)

todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %} Add Event {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			 <div class="col-6 offset-3">
			 	<h1 class="text-center my-3">Add an Event</h1>
			 	{% if error == True %}
			 		<p class="text-danger">Duplicate event found</p>
			 	{% endif %}
			 	<form action="{% url 'todolist:add_event' %}" method="post">
			 		{% csrf_token %}

			 		<div class="mb-3">
			 			<label for="event_name">Event Name:</label>
			 			<input
			 				type="text"
			 				name="event_name"
			 				class="form-control"
			 				id="event_name"
			 				value="{{ event_name }}"
			 				maxlength="50"
			 				required
			 				>
			 		</div>

			 		<div class="mb-3">
			 			<label for="description">Description:</label>
			 			<input
			 				type="text"
			 				name="description"
			 				class="form-control"
			 				id="description"
			 				value="{{ description }}"
			 				maxlength="500"
			 				required
			 				>
			 		</div>

			 		<div class="mb-3">
			 			<label for="description">Event Date:</label>
			 			<input
			 				type="date"
			 				name="event_date"
			 				class="form-control"
			 				id="event_date"
			 				value="{{ event_date }}"
			 				>
			 		</div>

			 		<div class="text-center">
						<input
							type="submit"
							class="btn btn-success"
							value="Add Event"
						>
					</div>

			 	</form>
			 </div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %} Add Task {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			 <div class="col-6 offset-3">
			 	<h1 class="text-center my-3">Add a Task</h1>
			 	{% if error == True %}
			 		<p class="text-danger">Duplicate task found</p>
			 	{% endif %}
			 	<form action="{% url 'todolist:add_task' %}" method="post">
			 		{% csrf_token %}

			 		<div class="mb-3">
			 			<label for="task_name">Task Name:</label>
			 			<input
			 				type="text"
			 				name="task_name"
			 				class="form-control"
			 				id="task_name"
			 				value="{{ task_name }}"
			 				maxlength="50"
			 				required
			 				>
			 		</div>

			 		<div class="mb-3">
			 			<label for="description">Description:</label>
			 			<input
			 				type="text"
			 				name="description"
			 				class="form-control"
			 				id="description"
			 				value="{{ description }}"
			 				maxlength="500"
			 				required
			 				>
			 		</div>

			 		<div class="text-center">
						<input
							type="submit"
							class="btn btn-success"
							value="Add Task"
						>
					</div>

			 	</form>
			 </div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/eventitem.html
{% extends 'base.html' %}

{% block title %}Event Item{% endblock %}

{% block content %}

	<div class="text-center my-3">
		
	<h1>{{ event_name }}</h1>
	<h3>Description:</h3>
	<p>{{ description }}</p>
	<h3>Status:</h3>
	<p>{{ status }}</p>
	<h3>Event Date:</h3>
	<p>{{ event_date }}</p>

	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
			Back to Events	
		</a>
	</button>

	</div>

{% endblock %}

todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
	{% if user.is_authenticated == True %}
		<h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class="container">
			<div class="row">
				<h3 class="text-center mt-5 mb-3">My Tasks</h3>

				{% if todoexists %}

					<ul class="list-group col-lg-2 offset-lg-5 text center">
						{% for todoitem in todoitem_list %}
							<li class="list-group-item text-center">

								<Strong>
								<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">{{ todoitem.task_name }}</a>
								</Strong>

							</li>
						{% endfor %}
					</ul>

				{% else %}

					<p class="text-center my-2">No tasks have been created.</p>

				{% endif %}

				<h3 class="text-center mt-5 mb-3">My Events</h3>

				{% if eventexists %}

					<ul class="list-group col-lg-2 offset-lg-5 text center">
						{% for eventitem in eventitem_list %}
							<li class="list-group-item text-center">

								<Strong>
									<a href="{% url 'todolist:vieweventitem' eventitem.id %}" class="text-decoration-none">{{ eventitem.event_name }}</a>
								</Strong>

							</li>
						{% endfor %}
					</ul>

				{% else %}
					<p class="text-center my-2">No events have been created.</p>
				{% endif %}

			</div>
		</div>

	{% else %}
	
		<h2 class="text-center my-3">You are not authorized to access this page.</h2>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}"> here.</a></p>

	{% endif %}

{% endblock %}


<!-- MVT Pattern - Model, View, Template -->

todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				{% if is_user_authenticated == False %}
					<h1>Something went wrong</h1>
					<p>Please contact your administrator.</p>
		
					<a href="{% url 'todolist:index' %}">Back to index page.</a>
				{% endif %}

				<form action="{% url 'todolist:login' %}" method="post">

					<!-- CSRF Token (Cross Site Request Forgeries)
					all forms in Django should contain this csrf token to make sure that the form request is coming from tohe same django project. If not, django will block the request -->

					{% csrf_token %}

					<div class="mb-3">
						<label for="username">Username:</label>
						<input
							type="text"
							name="username"
							class="form-control"
							id="username"
							maxlength="20"
							value="{{ username }}"
							required
						>
					</div>

					<div class="mb-3">
						<label for="password">Password:</label>
						<input
							type="password"
							name="password"
							class="form-control"
							id="password"
							maxlength="20"
							value="{{ password }}"
							required
						>
					</div>

					<div class="text-center">
						<input
							type="submit"
							class="btn btn-success"
							value="Login"
						>
					</div>
					
				</form>
			</div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/register.html
{% extends 'base.html' %}

	{% block title %}Register{% endblock %}
	{% block content %}
	<div class="text-center">

		{% if is_user_registered == True %}
			<h1>Duplicate User Found!</h1>
			<p>A duplicate user has been found, user creation unsuccessful!</p>

		{% else %}
			<h1>User Successfully Createed!</h1>
			<p>The account for {{first_name}} {{last_name}} has been created!</p>

		{% endif %}

	</div>
	{% endblock %}

todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Todo Item{% endblock %}

{% block content %}

	<div class="text-center my-3">
		
	<h1>{{ task_name }}</h1>
	<h3>Description:</h3>
	<p>{{ description }}</p>
	<h3>Status:</h3>
	<p>{{ status }}</p>

	<button class="btn btn-success mx-1 text-decoration-none">
		<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">
			Edit Task	
		</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none">
		<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">
			Delete Task	
		</a>
	</button>

	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
			Back to Index	
		</a>
	</button>

	</div>

{% endblock %}

todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

	{% block title %}Update Profile{% endblock %}

	{% block content %}
		{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Profile</h1>
					{% if error == True %}
						<p class="text-danger">Profile not found</p>
					{% endif %}
					<form action="{% url 'todolist:update_profile' %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="first_name">First Name: </label>
						    <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="last_name">First Name: </label>
						    <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="password">Password: </label>
						    <input class="form-control" id="password" type="text" name="password" value="{{ password }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Profile">
						</div>

					</form>
				</div>
			</div>
		</div>
		{% else %}
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here.</a></p>
		{% endif %}
	{% endblock %}

todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

	{% block title %}Update Task{% endblock %}

	{% block content %}
		{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Task</h1>
					{% if error == True %}
						<p class="text-danger">Task not found</p>
					{% endif %}
					<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="task_name">Task Name: </label>
						    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
						    <label for="status">Status: </label>
						    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Task">
						</div>

					</form>
				</div>
			</div>
		</div>
		{% else %}
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		{% endif %}
	{% endblock %}